name: Mark stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: 'stale'
        stale-issue-message: 'This issue has been marked stale because it has been open 30 days with no activity. If you are still hitting this issue, please remove the stale label and/or add provide more details.'
        skip-stale-issue-message: true
        days-before-stale: 30
        days-before-close: -1
        
